# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  configuration: Release

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 3.1.x
    
- task: DotNetCoreCLI@2
  displayName: 'Build (Ramble)'
  inputs:
    command: build
    projects: 'src/**/*.csproj'
    arguments: '--configuration $(configuration)'

- task: DotNetCoreCLI@2
  displayName: 'Run tests (Ramble)'
  inputs:
    command: test
    projects: 'src/**/*Tests/*.csproj'
    arguments: '--configuration $(configuration)'